### ISSUE TITLE
Why not create a Docker for choice a laravel version?

### ISSUE THREAD

**Issue by ssheduardo** [dimadeush/docker-nginx-php-laravel#7]
Your docker is very good, but why not create a empty Docker minimal for install manually a Laravel for example 5.8, 6.0, etc. without package extra?

Good job.

**Comment by dimadeush** [comment]
Hello
The main idea of docker-nginx-php-laravel repo is to have "ready for use" environment with latest laravel version. Empty docker environment is good idea and maybe will create it when will have time. 
In any case, it is not "big deal" to delete related to laravel files and folders after checkout from this repo and install everything what you need.
